In [3]:
df = pd.read_excel('data/titanic.xlsx')

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [11]:
df1 = pd.read_excel('data/titanic.xlsx', sheet_name='titanic class 1')

In [13]:
df2 = pd.read_excel('data/titanic.xlsx', sheet_name='titanic class 2')

In [ ]:
df1 = df1[['PassengerId', 'Survived', 'Pclass', 'Sex', 'Embarked']]
df2 = df2[['PassengerId', 'Survived', 'Pclass', 'Embarked']]
df_fin = pd.concat([df1, df2], axis=1)
df_fin

,PassengerId,Survived,Pclass,Sex,Embarked,PassengerId,Survived,Pclass,Embarked
0,1,1,1,female,C,1.0,1.0,2.0,C
1,2,1,1,female,S,2.0,1.0,2.0,S
2,3,0,1,male,S,3.0,1.0,2.0,S
3,4,1,1,female,S,4.0,0.0,2.0,S
4,5,1,1,male,S,5.0,1.0,2.0,S
...,...,...,...,...,...,...,...,...,...
211,212,1,1,female,S,NaN,NaN,NaN,NaN
212,213,0,1,male,S,NaN,NaN,NaN,NaN
213,214,1,1,female,C,NaN,NaN,NaN,NaN
214,215,1,1,female,S,NaN,NaN,NaN,NaN
215,216,1,1,male,C,NaN,NaN,NaN,NaN

In [ ]:
df_fin = pd.concat([df1, df2], axis=0, join='outer')
df_fin

     PassengerId  Survived  Pclass     Sex Embarked
0              1         1       1  female        C
1              2         1       1  female        S
2              3         0       1    male        S
3              4         1       1  female        S
4              5         1       1    male        S
..           ...       ...     ...     ...      ...
179          180         1       2     NaN        C
180          181         1       2     NaN        C
181          182         1       2     NaN        S
182          183         0       2     NaN        S
183          184         0       2     NaN        S

[400 rows x 5 columns]

In [ ]:
df_fin = pd.concat([df1, df2], axis=0, join='inner')
df_fin

     PassengerId  Survived  Pclass Embarked
0              1         1       1        C
1              2         1       1        S
2              3         0       1        S
3              4         1       1        S
4              5         1       1        S
..           ...       ...     ...      ...
179          180         1       2        C
180          181         1       2        C
181          182         1       2        S
182          183         0       2        S
183          184         0       2        S

[400 rows x 4 columns]

In [ ]:
df_fin = pd.merge(df1, df2, on='PassengerId')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S

In [ ]:
df_fin = pd.merge(df1, df2, on='PassengerId', how='left')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1.0,2.0,C
1,2,1,1,female,S,1.0,2.0,S
2,3,0,1,male,S,1.0,2.0,S
3,4,1,1,female,S,0.0,2.0,S
4,5,1,1,male,S,1.0,2.0,S
...,...,...,...,...,...,...,...,...
211,212,1,1,female,S,NaN,NaN,NaN
212,213,0,1,male,S,NaN,NaN,NaN
213,214,1,1,female,C,NaN,NaN,NaN
214,215,1,1,female,S,NaN,NaN,NaN
215,216,1,1,male,C,NaN,NaN,NaN

In [ ]:
df_fin = pd.merge(df1, df2, on='PassengerId', how='right')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S

In [ ]:
df_fin = pd.merge(df1, df2, on='PassengerId', how='outer')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1.0,2.0,C
1,2,1,1,female,S,1.0,2.0,S
2,3,0,1,male,S,1.0,2.0,S
3,4,1,1,female,S,0.0,2.0,S
4,5,1,1,male,S,1.0,2.0,S
...,...,...,...,...,...,...,...,...
211,212,1,1,female,S,NaN,NaN,NaN
212,213,0,1,male,S,NaN,NaN,NaN
213,214,1,1,female,C,NaN,NaN,NaN
214,215,1,1,female,S,NaN,NaN,NaN
215,216,1,1,male,C,NaN,NaN,NaN

In [ ]:
df_fin = pd.merge(df1, df2, left_on='PassengerId', right_on='PassengerId')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S

In [ ]:
df_fin = pd.merge(df1, df2, left_on='PassengerId', right_on='PassengerId', suffixes=('_left', '_right'))
df_fin

,PassengerId,Survived_left,Pclass_left,Sex,Embarked_left,Survived_right,Pclass_right,Embarked_right
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S