In [1]:
import pandas as pd

In [5]:
df = pd.read_excel('titanic.xlsx')

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [1]:
df = pd.read_excel('titanic.xlsx')

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

In [4]:
df = pd.read_excel('titanic.xlsx')

ValueError: Excel file format cannot be determined, you must specify an engine manually.

In [ ]:
df = pd.read_excel('data/titanic.xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.

In [6]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]━━ 1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [7]:
df = pd.read_excel('titanic.xlsx')

In [8]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
df1 = pd.read_excel('titanic.xlsx', sheet_name='titanic class 1')

In [ ]:
df1 = pd.read_excel('data/titanic.xlsx', sheet_name='titanic class 1')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
1,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
3,4,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
4,5,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [14]:
df2 = pd.read_excel('titanic.xlsx', sheet_name='titanic class 2')

In [ ]:
df2 = pd.read_excel('data/titanic.xlsx', sheet_name='titanic class 2')

In [16]:
df_fin

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
1,2,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
3,4,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
4,5,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
...,...,...,...,...,...,...,...,...,...,...,...,...
179,180,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
180,181,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
181,182,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
182,183,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
183,184,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S

In [20]:
df1 = df1[['PassengerId', 'Survived', 'Pclass', 'Sex', 'Embarked']]
df2 = df2[['PassengerId', 'Survived', 'Pclass', 'Embarked']]
df_fin = pd.concat([df1, df2], axis=1)
df_fin

,PassengerId,Survived,Pclass,Sex,Embarked,PassengerId,Survived,Pclass,Embarked
0,1,1,1,female,C,1.0,1.0,2.0,C
1,2,1,1,female,S,2.0,1.0,2.0,S
2,3,0,1,male,S,3.0,1.0,2.0,S
3,4,1,1,female,S,4.0,0.0,2.0,S
4,5,1,1,male,S,5.0,1.0,2.0,S
...,...,...,...,...,...,...,...,...,...
211,212,1,1,female,S,NaN,NaN,NaN,NaN
212,213,0,1,male,S,NaN,NaN,NaN,NaN
213,214,1,1,female,C,NaN,NaN,NaN,NaN
214,215,1,1,female,S,NaN,NaN,NaN,NaN
215,216,1,1,male,C,NaN,NaN,NaN,NaN

In [21]:
df_fin = pd.concat([df1, df2], axis=0, join='outer')
df_fin

     PassengerId  Survived  Pclass     Sex Embarked
0              1         1       1  female        C
1              2         1       1  female        S
2              3         0       1    male        S
3              4         1       1  female        S
4              5         1       1    male        S
..           ...       ...     ...     ...      ...
179          180         1       2     NaN        C
180          181         1       2     NaN        C
181          182         1       2     NaN        S
182          183         0       2     NaN        S
183          184         0       2     NaN        S

[400 rows x 5 columns]

In [22]:
df_fin = pd.concat([df1, df2], axis=0, join='inner')
df_fin

     PassengerId  Survived  Pclass Embarked
0              1         1       1        C
1              2         1       1        S
2              3         0       1        S
3              4         1       1        S
4              5         1       1        S
..           ...       ...     ...      ...
179          180         1       2        C
180          181         1       2        C
181          182         1       2        S
182          183         0       2        S
183          184         0       2        S

[400 rows x 4 columns]

In [26]:
df_fin = pd.merge(df1, df2, on='PassengerId')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S

In [28]:
df_fin = pd.merge(df1, df2, on='PassengerId', how='left')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1.0,2.0,C
1,2,1,1,female,S,1.0,2.0,S
2,3,0,1,male,S,1.0,2.0,S
3,4,1,1,female,S,0.0,2.0,S
4,5,1,1,male,S,1.0,2.0,S
...,...,...,...,...,...,...,...,...
211,212,1,1,female,S,NaN,NaN,NaN
212,213,0,1,male,S,NaN,NaN,NaN
213,214,1,1,female,C,NaN,NaN,NaN
214,215,1,1,female,S,NaN,NaN,NaN
215,216,1,1,male,C,NaN,NaN,NaN

In [29]:
df_fin = pd.merge(df1, df2, on='PassengerId', how='right')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S

In [30]:
df_fin = pd.merge(df1, df2, on='PassengerId', how='outer')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1.0,2.0,C
1,2,1,1,female,S,1.0,2.0,S
2,3,0,1,male,S,1.0,2.0,S
3,4,1,1,female,S,0.0,2.0,S
4,5,1,1,male,S,1.0,2.0,S
...,...,...,...,...,...,...,...,...
211,212,1,1,female,S,NaN,NaN,NaN
212,213,0,1,male,S,NaN,NaN,NaN
213,214,1,1,female,C,NaN,NaN,NaN
214,215,1,1,female,S,NaN,NaN,NaN
215,216,1,1,male,C,NaN,NaN,NaN

In [33]:
df_fin = pd.merge(df1, df2, left_on='PassengerId', right_on='PassengerId')
df_fin

,PassengerId,Survived_x,Pclass_x,Sex,Embarked_x,Survived_y,Pclass_y,Embarked_y
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S

In [34]:
df_fin = pd.merge(df1, df2, left_on='PassengerId', right_on='PassengerId', suffixes=('_left', '_right'))
df_fin

,PassengerId,Survived_left,Pclass_left,Sex,Embarked_left,Survived_right,Pclass_right,Embarked_right
0,1,1,1,female,C,1,2,C
1,2,1,1,female,S,1,2,S
2,3,0,1,male,S,1,2,S
3,4,1,1,female,S,0,2,S
4,5,1,1,male,S,1,2,S
...,...,...,...,...,...,...,...,...
179,180,1,1,male,C,1,2,C
180,181,1,1,male,S,1,2,C
181,182,0,1,male,S,1,2,S
182,183,1,1,female,C,0,2,S
183,184,0,1,male,S,0,2,S